<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>opencast-security-cas-client-wrapper</artifactId>
  <name>Opencast :: security-cas-client-wrapper</name>
  <packaging>bundle</packaging>
  <parent>
    <groupId>org.opencastproject</groupId>
    <artifactId>base</artifactId>
    <version>21-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <properties>
    <opencast.basedir>${project.basedir}/../..</opencast.basedir>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.jasig.cas.client</groupId>
      <artifactId>cas-client-core</artifactId>
    </dependency>
    <!-- These are dependencies of cas-client-core gotten with 'mvn dependency:tree' -->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcpkix-jdk18on</artifactId>
      <version>1.78.1</version>
    </dependency>
    <dependency>
      <groupId>javax.xml.bind</groupId>
      <artifactId>jaxb-api</artifactId>
      <version>2.3.1</version>
    </dependency>
    <dependency>
      <groupId>org.glassfish.jaxb</groupId>
      <artifactId>jaxb-core</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <ignoredUnusedDeclaredDependencies>
            <!-- provide a logger for tests -->
            <ignoredUnusedDeclaredDependency>org.slf4j:slf4j-api:jar</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>org.jasig.cas.client:cas-client-core</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>com.fasterxml.jackson.core:jackson-databind</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>commons-codec:commons-codec</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>org.bouncycastle:bcpkix-jdk18on</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>javax.xml.bind:jaxb-api</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>org.glassfish.jaxb:jaxb-core</ignoredUnusedDeclaredDependency>
          </ignoredUnusedDeclaredDependencies>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Embed-Dependency>cas-client-core</Embed-Dependency>
            <Embed-Transitive>false</Embed-Transitive>
            <Import-Package>
              com.fasterxml.jackson.annotation;version="[2.17,3)",
              com.fasterxml.jackson.core;version="[2.17,3)",
              com.fasterxml.jackson.databind;version="[2.17,3)",
              org.apache.commons.codec.binary;version="[1.15,2)",
              org.bouncycastle.jce.provider;version="[1.70,2)",
              org.bouncycastle.openssl;version="[1.70,2)",
              org.bouncycastle.openssl.jcajce;version="[1.70,2)",
              *
            </Import-Package>
            <Export-Package>
              org.jasig.cas.client;version=3.6.4,
              org.jasig.cas.client.configuration;version=3.6.4,
              org.jasig.cas.client.ssl;version=3.6.4,
              org.jasig.cas.client.proxy;version=3.6.4,
              org.jasig.cas.client.util;version=3.6.4,
              org.jasig.cas.client.jaas;version=3.6.4,
              org.jasig.cas.client.authentication;version=3.6.4,
              org.jasig.cas.client.validation;version=3.6.4,
              org.jasig.cas.client.session;version=3.6.4,
              org.jasig.cas.client.ssl;version=3.6.4
            </Export-Package>
          </instructions>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
