#!/bin/bash
###
##  Copyright 2009, 2010 The Regents of the University of California
##  Licensed under the Educational Community License, Version 2.0
##  (the "License"); you may not use this file except in compliance
##  with the License. You may obtain a copy of the License at
##
##  http://www.osedu.org/licenses/ECL-2.0
##
##  Unless required by applicable law or agreed to in writing,
##  software distributed under the License is distributed on an "AS IS"
##  BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
##  or implied. See the License for the specific language governing
##  permissions and limitations under the License.
##
### 

function usage {
    echo \
"upload.sh -d directory [-u username][-p password][-s server url][-t time][-h]

    -d directory
        The directory that you want to upload your files from
        generated by 'convert.sh'
    -s server url
        the URL of the server you want to upload to
        defaults to http://localhost:8080/
    -u username
        the username required to log into the server
        defaults to 'admin'
    -p password
        the password required to log into the server
        defaults to 'opencast'
    -t time 
        the time between posting media to the server
        defaults to '3m' or 3 minutes
    -h
        displays this help message
";
    
}

server="http://localhost:8080/"
directory="";
username="admin"
password="opencast"
delay="3m"
while getopts “hu:p:s:d:” OPTION
do
	case $OPTION in
	h)
	  usage
	  exit 1
	  ;;
	s)
      server=$OPTARG
	  ;;
	d)
	  directory=$OPTARG
	  ;;
	u)
	  username=$OPTARG
	  ;;
	u)
	  password=$OPTARG
	  ;;
    t)
      delay=$OPTARG
      ;;
	?)
	  usage
	  exit
	  ;;
	esac
done

if [[ $server != */ ]] 
then
    server=$server"/"  
fi 

curl -c cookies.txt $server"ingest/addMediaPackage" \
    -H "X-Requested-Auth: Digest" \
    --digest --user $username:$password \

if [ -d $directory ]
then
    cd $directory 
    date=(date +"%B %e %Y")
    for i in * 
    do
        echo "ingesting $i into $server"
        if [[ $i == s-* ]] 
        then
            curl -v -o /dev/null -b ../cookies.txt $server"ingest/addMediaPackage" \
             	--form-string "title=$i" \
	            --form-string "creator=TestScript" \
	            --form-string "flavor=presentation/source" \
	            --form track=@$i;
        else
            curl -v -o /dev/null -b ../cookies.txt $server"ingest/addMediaPackage" \
             	--form-string "title=$i" \
	            --form-string "creator=TestScript" \
	            --form-string "flavor=presenter/source" \
	            --form track=@$i;
        fi
        sleep $delay
    done
    cd ..
fi
rm cookies.txt


    




