#!/bin/sh

set -eux

# Ensure the distribution tarballs exist
test $(ls -1 build/*tar.gz | grep 'dist-admin-\|dist-presentation-\|dist-worker-' | wc -l) -eq 3

# Remove old data directories
cd build
find * -maxdepth 0 -type d -exec echo '{}' \; -exec rm -rI '{}' \;

tar xf opencast-dist-admin-*.tar.gz
tar xf opencast-dist-presentation-*.tar.gz
tar xf opencast-dist-worker-*.tar.gz

mkdir -p shared-storage
ln -s ../../shared-storage opencast-dist-admin/data/opencast
ln -s ../../shared-storage opencast-dist-presentation/data/opencast
ln -s ../../shared-storage opencast-dist-worker/data/opencast

sed -i 's_localhost:8080_localhost:8081_' opencast-dist-presentation/etc/custom.properties
sed -i 's_localhost:8080_localhost:8082_' opencast-dist-worker/etc/custom.properties

sed -i 's_port=8080_port=8081_' opencast-dist-presentation/etc/org.ops4j.pax.web.cfg
sed -i 's_port=8080_port=8082_' opencast-dist-worker/etc/org.ops4j.pax.web.cfg

for node in admin presentation worker; do
  # configure database
  sed -i 's_^.*db.jdbc.driver=.*$_org.opencastproject.db.jdbc.driver=org.postgresql.Driver_' \
    "opencast-dist-${node}/etc/custom.properties"
  sed -i 's_^.*db.jdbc.url=.*$_org.opencastproject.db.jdbc.url=jdbc:postgresql://127.0.0.1/opencast_' \
    "opencast-dist-${node}/etc/custom.properties"
  sed -i 's_^.*db.jdbc.user=.*$_org.opencastproject.db.jdbc.user=opencast_' \
    "opencast-dist-${node}/etc/custom.properties"
  sed -i 's_^.*db.jdbc.pass=.*$_org.opencastproject.db.jdbc.pass=dbpassword_' \
    "opencast-dist-${node}/etc/custom.properties"

  # configure organization
  sed -i 's_^.*admin.ui.url=.*$_prop.org.opencastproject.admin.ui.url=http://localhost:8080_' \
    "opencast-dist-${node}/etc/org.opencastproject.organization-mh_default_org.cfg"
  sed -i 's_^.*engage.ui.url=.*$_prop.org.opencastproject.engage.ui.url=http://localhost:8081_' \
    "opencast-dist-${node}/etc/org.opencastproject.organization-mh_default_org.cfg"
  sed -i 's_^.*file.repo.url=.*$_prop.org.opencastproject.file.repo.url=${prop.org.opencastproject.admin.ui.url}_' \
    "opencast-dist-${node}/etc/org.opencastproject.organization-mh_default_org.cfg"
done

sed -i 's_^.*dispatch.interval=.*$_dispatch.interval=2_' opencast-dist-admin/etc/org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.cfg
sed -i 's_^.*dispatch.interval=.*$_dispatch.interval=0_' opencast-dist-presentation/etc/org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.cfg
sed -i 's_^.*dispatch.interval=.*$_dispatch.interval=0_' opencast-dist-worker/etc/org.opencastproject.serviceregistry.impl.ServiceRegistryJpaImpl.cfg

# start services
cd ../docs/scripts/devel-dependency-containers/
docker-compose -f docker-compose-postgresql.yml down
docker-compose -f docker-compose-postgresql.yml up -d
