project_identifier: opencast-community
base_path: .
preserve_hierarchy: true

files:
  -
    source: '/modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-en_US.json'
    translation: '/modules/admin-ui-frontend/resources/public/org/opencastproject/adminui/languages/lang-%locale_with_underscore%.json'

  -
    source: '/modules/engage-theodul-core/src/main/resources/ui/language/en-US.json'
    translation: '/modules/engage-theodul-core/src/main/resources/ui/language/%locale%.json'

  -
    source: '/modules/**/src/main/resources/static/language/en-US.json'
    translation: '/%original_path%/%locale%.json'

  -
    source: '/modules/engage-ui/src/main/resources/ui/language/en-US.json'
    translation: '/modules/engage-ui/src/main/resources/ui/language/%locale%.json'

  -
    source: '/modules/engage-paella-player/src/main/paella-opencast/plugins/**/localization/en-US.json'
    translation: '/modules/engage-paella-player/src/main/paella-opencast/plugins/**/localization/%locale%.json'

  -
    source: '/modules/lti/src/i18n/en-US.json'
    translation: '/modules/lti/src/i18n/%locale%.json'
