/**
 *  Copyright 2009, 2010 The Regents of the University of California
 *  Licensed under the Educational Community License, Version 2.0
 *  (the "License"); you may not use this file except in compliance
 *  with the License. You may obtain a copy of the License at
 *
 *  http://www.osedu.org/licenses/ECL-2.0
 *
 *  Unless required by applicable law or agreed to in writing,
 *  software distributed under the License is distributed on an "AS IS"
 *  BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 *  or implied. See the License for the specific language governing
 *  permissions and limitations under the License.
 *
 */
package org.opencastproject.distribution.youtube;

import org.opencastproject.deliver.schedule.Schedule;
import org.opencastproject.deliver.schedule.Task;
import org.opencastproject.deliver.store.InvalidKeyException;
import org.opencastproject.deliver.youtube.YouTubeConfiguration;
import org.opencastproject.deliver.youtube.YouTubeDeliveryAction;
import org.opencastproject.deliver.youtube.YouTubeRemoveAction;
import org.opencastproject.distribution.api.DistributionException;
import org.opencastproject.distribution.api.DistributionService;
import org.opencastproject.job.api.AbstractJobProducer;
import org.opencastproject.job.api.Job;
import org.opencastproject.mediapackage.MediaPackageElement;
import org.opencastproject.mediapackage.MediaPackageElementBuilderFactory;
import org.opencastproject.mediapackage.MediaPackageElementParser;
import org.opencastproject.mediapackage.MediaPackageException;
import org.opencastproject.serviceregistry.api.ServiceRegistry;
import org.opencastproject.serviceregistry.api.ServiceRegistryException;
import org.opencastproject.util.NotFoundException;
import org.opencastproject.workspace.api.Workspace;

import org.apache.commons.lang.StringUtils;
import org.osgi.service.component.ComponentContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Arrays;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/**
 * Distributes media to a Youtube play list.
 */
public class YoutubeDistributionService extends AbstractJobProducer implements DistributionService {

  /** Receipt type */
  public static final String JOB_TYPE = "org.opencastproject.distribution.youtube";

  /** logger instance */
  private static final Logger logger = LoggerFactory.getLogger(YoutubeDistributionService.class);

  /** List of available operations on jobs */
  private enum Operation {
    Distribute, Retract
  };

  /** workspace instance */
  protected Workspace workspace = null;

  /** The remote service registry */
  protected ServiceRegistry serviceRegistry = null;

  /** Youtube configuration instance */
  private static YouTubeConfiguration config = null;

  /** playlist ID */
  private static String destination = null;

  /** URL for uploading */
  private static final String uploadURL = "http://uploads.gdata.youtube.com/feeds/api/users/default/uploads";

  /** category of the video - default to "Education" */
  private static final String category = "Education";

  /** prefix of the URL generated by gdata API */
  private static final String gdataURLPrefix = "http://gdata.youtube.com/feeds/api/users/utubedelivery/uploads/";

  /** prefix of the Youtube URL */
  private static final String youtubeURLPrefix = "http://www.youtube.com/watch?v=";

  /** only one scheduler instance for this service */
  private static Schedule schedule = null;

  /** context strategy for the distribution service */
  YoutubeDistributionContextStrategy contextStrategy = null;

  /** The executor service used to queue and run jobs */
  private ExecutorService executor = null;

  /**
   * Creates a new instance of the youtube distribution service.
   */
  public YoutubeDistributionService() {
    super(JOB_TYPE);
  }

  /**
   * Called when service activates. Defined in OSGi resource file.
   */
  public void activate(ComponentContext cc) {
    String username = cc.getBundleContext().getProperty("youtube.username"); // "utubedelivery"
    String password = cc.getBundleContext().getProperty("youtube.password"); // "utubedelivery"
    String clientid = cc.getBundleContext().getProperty("youtube.clientid"); // "abcde"
    String developerkey = cc.getBundleContext().getProperty("youtube.developerkey");
    // "AI39si7bx2AbnOM6RM8J7mdrljfZCzisYzDkqvIqEjV3zjbqQIr6-u_bg3R0MLAVVXLqKjSsxu4ReytWFn7ylIlDk6OC7pdXpQ"

    config = YouTubeConfiguration.getInstance();
    // client ID may not be necessary
    config.setClientId(clientid);
    config.setDeveloperKey(developerkey);
    config.setUploadUrl(uploadURL);
    config.setUserId(username);
    config.setPassword(password);
    config.setCategory(category);

    // create context strategy
    contextStrategy = new YoutubeDistributionContextStrategy();
    // default destination
    destination = cc.getBundleContext().getProperty("youtube.playlist"); // "B8B47104C2C1663B"

    // create the scheduler using file system store
    String directory_name = cc.getBundleContext().getProperty("youtube.task");
    if (directory_name == null || directory_name.equals("")) {
      directory_name = "/tmp/youtube";
    }
    logger.info("Task file directory: {}", directory_name);
    File data_directory = new File(directory_name);
    data_directory.mkdirs();
    try {
      schedule = new Schedule(data_directory);
    } catch (InvalidKeyException e) {
      throw new IllegalStateException(e);
    }

    int threads = 1;
    String threadsConfig = StringUtils.trimToNull(cc.getBundleContext().getProperty(
            "org.opencastproject.distribution.youtube.threads"));
    if (threadsConfig != null) {
      try {
        threads = Integer.parseInt(threadsConfig);
      } catch (NumberFormatException e) {
        logger.warn("Youtube distribution threads configuration is malformed: '{}'", threadsConfig);
      }
    }
    executor = Executors.newFixedThreadPool(threads);
  }

  /**
   * Called when service deactivates. Defined in OSGi resource file.
   */
  public void deactivate() {
    // shutdown the scheduler
    schedule.shutdown();
    executor.shutdown();
  }

  /**
   * Gets task name given the media package ID and the track ID.
   * 
   * @param mediaPackge
   *          ID of the package
   * @param track
   *          ID of the track
   * @return task identifier
   */
  private String getTaskID(String mediaPackage, String track) {
    // use "YOUTUBE" + media package identifier + track identifier as task identifier
    return "YOUTUBE-" + mediaPackage.replaceAll("\\.", "-") + "-" + track;
  }

  /**
   * {@inheritDoc}
   * 
   * @see org.opencastproject.distribution.api.DistributionService#distribute(java.lang.String,
   *      org.opencastproject.mediapackage.MediaPackageElement)
   */
  @Override
  public Job distribute(String mediaPackageId, MediaPackageElement element) throws DistributionException,
          MediaPackageException {

    if (mediaPackageId == null)
      throw new MediaPackageException("Mediapackage ID must be specified");
    if (element == null)
      throw new MediaPackageException("Mediapackage element must be specified");

    try {
      return serviceRegistry.createJob(JOB_TYPE, Operation.Distribute.toString(),
              Arrays.asList(mediaPackageId, MediaPackageElementParser.getAsXml(element)));
    } catch (ServiceRegistryException e) {
      throw new DistributionException("Unable to create a job", e);
    }
  }

  /**
   * Distributes the element to the distribution channel and returns a reference to the distributed version of the
   * element.
   * 
   * @param job
   *          the associated job
   * @param mediaPackageId
   *          the mediapackage identifier
   * @param element
   *          the element to distribute
   * @return the distributed element
   * @throws DistributionException
   *           if distribution fails
   * @throws MediaPackageException
   *           if the mediapackage is in an inconsistent state
   */
  private MediaPackageElement distribute(Job job, String mediaPackageId, MediaPackageElement element)
          throws DistributionException, MediaPackageException {

    if (mediaPackageId == null)
      throw new IllegalArgumentException("Mediapackage ID must be specified");
    if (element == null)
      throw new IllegalArgumentException("Mediapackage element must be specified");
    if (element.getIdentifier() == null)
      throw new IllegalArgumentException("Mediapackage element must have an identifier");

    try {
      File sourceFile;
      try {
        sourceFile = workspace.get(element.getURI());
      } catch (NotFoundException e) {
        throw new DistributionException("Unable to find " + element.getURI() + " in the workspace", e);
      } catch (IOException e) {
        throw new DistributionException("Error loading " + element.getURI() + " from the workspace", e);
      }

      // get task name
      String name = getTaskID(mediaPackageId, element.getIdentifier());

      // check if the file has already been delivered
      Task savedTask;
      try {
        savedTask = schedule.getSavedTask(name);
      } catch (InvalidKeyException e) {
        throw new DistributionException(e);
      }

      if (savedTask != null && savedTask.getState() == Task.State.COMPLETE) {
        // has been successfully delivered
        // remove the media
        remove(name);
      }

      YouTubeDeliveryAction act = new YouTubeDeliveryAction();
      act.setName(name);
      act.setTitle(sourceFile.getName());
      // CHNAGE ME: set metadata elements here
      act.setTags(new String[] { "whatever" });
      act.setAbstract("Opencast Distribution Service - Youtube");
      act.setMediaPath(sourceFile.getAbsolutePath());

      // get playlist ID from context strategy
      String contextDestination = contextStrategy.getContextName(mediaPackageId);
      if (contextDestination != null) {
        // use the destination from context strategy
        destination = contextDestination;
      }

      // deliver to a play list
      act.setDestination(destination); // FIXME: replace this with a playlist based on the episode's series

      logger.info("Delivering from {}", sourceFile.getAbsolutePath());

      // start the scheduler
      try {
        schedule.start(act);
      } catch (InvalidKeyException e) {
        throw new DistributionException(e);
      }

      MediaPackageElement distributedElement = null;

      while (true) {
        Task task;
        try {
          task = schedule.getTask(name);
        } catch (InvalidKeyException e) {
          throw new DistributionException(e);
        }

        synchronized (task) {
          Task.State state = task.getState();
          if (state == Task.State.INITIAL || state == Task.State.ACTIVE) {
            try {
              Thread.sleep(1000L);
            } catch (Exception e) {
              throw new RuntimeException(e);
            }
            // still running
            continue;
          } else if (state == Task.State.COMPLETE) {
            logger.info("Succeeded delivering from {}", sourceFile.getAbsolutePath());
            String videoURL = act.getEntryUrl();
            // convert the entry URL to a user-oriented URL
            videoURL = videoURL.replace("?client=" + config.getClientId(), "");
            videoURL = videoURL.replace(gdataURLPrefix, youtubeURLPrefix);
            URI newTrackUri;
            try {
              newTrackUri = new URI(videoURL);
            } catch (URISyntaxException e) {
              throw new DistributionException("Distributed element produces an invalid URI", e);
            }
            distributedElement = MediaPackageElementBuilderFactory.newInstance().newElementBuilder()
                    .elementFromURI(newTrackUri, element.getElementType(), element.getFlavor());
            distributedElement.setIdentifier(element.getIdentifier() + "-dist");

            return distributedElement;
          } else if (state == Task.State.FAILED) {
            throw new DistributionException("Failed delivering " + sourceFile.getAbsolutePath());
          }
        }
      } // end of schedule loop

    } catch (Exception e) {
      logger.warn("Error distributing " + element, e);
      if (e instanceof DistributionException) {
        throw (DistributionException) e;
      } else {
        throw new DistributionException(e);
      }
    }
  }

  /**
   * {@inheritDoc}
   * 
   * @see org.opencastproject.distribution.api.DistributionService#retract(java.lang.String)
   */
  @Override
  public Job retract(String mediaPackageId) throws DistributionException {

    if (mediaPackageId == null)
      throw new IllegalArgumentException("Mediapackage ID must be specified");

    try {
      return serviceRegistry.createJob(JOB_TYPE, Operation.Retract.toString(), Arrays.asList(mediaPackageId));
    } catch (ServiceRegistryException e) {
      throw new DistributionException("Unable to create a job", e);
    }
  }

  /**
   * Retracts the mediapackage from YouTube.
   * 
   * @param job
   *          the associated job
   * @param mediapackageId
   *          the mediapackage
   * @throws DistributionException
   *           if retract did not work
   */
  private void retract(Job job, String mediapackageId) throws DistributionException {
    throw new DistributionException("Retract from YouTube has not been implemented");
  }

  /**
   * Removes the media delivered by the given task.
   * 
   * @param name
   *          task identifier
   */
  private void remove(String name) throws DistributionException {
    logger.info("Publish task: {}", name);

    YouTubeRemoveAction ract = new YouTubeRemoveAction();
    ract.setName(name + "_r");
    ract.setPublishTask(name);
    try {
      schedule.start(ract);
    } catch (InvalidKeyException e) {
      throw new DistributionException(e);
    }

    while (true) {
      Task rTask;
      try {
        rTask = schedule.getTask(name + "_r");
      } catch (InvalidKeyException e) {
        throw new DistributionException(e);
      }
      synchronized (rTask) {
        Task.State state = rTask.getState();
        if (state == Task.State.INITIAL || state == Task.State.ACTIVE) {
          try {
            Thread.sleep(1000L);
          } catch (Exception e) {
            throw new RuntimeException(e);
          }
          // still running
          continue;
        } else if (state == Task.State.COMPLETE) {
          logger.info("Succeeded retracting media");
          break;
        } else if (state == Task.State.FAILED) {
          // fail to remove
          throw new DistributionException("Failed to remove media");
        }
      } // end of synchronized
    } // end of schedule loop
  }

  /**
   * {@inheritDoc}
   * 
   * @see org.opencastproject.job.api.AbstractJobProducer#process(org.opencastproject.job.api.Job)
   */
  @Override
  protected String process(Job job) throws Exception {
    Operation op = null;
    try {
      op = Operation.valueOf(job.getOperation());
      List<String> arguments = job.getArguments();
      String mediapackageId = arguments.get(0);
      switch (op) {
        case Distribute:
          MediaPackageElement sourceElement = MediaPackageElementParser.getFromXml(arguments.get(1));
          MediaPackageElement distributedElement = distribute(job, mediapackageId, sourceElement);
          return (distributedElement != null) ? MediaPackageElementParser.getAsXml(distributedElement) : null;
        case Retract:
          retract(job, mediapackageId);
          return null;
        default:
          throw new IllegalStateException("Don't know how to handle operation '" + job.getOperation() + "'");
      }
    } catch (IllegalArgumentException e) {
      throw new ServiceRegistryException("This service can't handle operations of type '" + op + "'");
    } catch (IndexOutOfBoundsException e) {
      throw new ServiceRegistryException("This argument list for operation '" + op + "' does not meet expectations");
    } catch (Exception e) {
      throw new ServiceRegistryException("Error handling operation '" + op + "'");
    }
  }

  /**
   * Callback for the OSGi environment to set the workspace reference.
   * 
   * @param workspace
   *          the workspace
   */
  protected void setWorkspace(Workspace workspace) {
    this.workspace = workspace;
  }

  /**
   * Callback for the OSGi environment to set the service registry reference.
   * 
   * @param serviceRegistry
   *          the service registry
   */
  protected void setServiceRegistry(ServiceRegistry serviceRegistry) {
    this.serviceRegistry = serviceRegistry;
  }
  
  /**
   * {@inheritDoc}
   * @see org.opencastproject.job.api.AbstractJobProducer#getServiceRegistry()
   */
  @Override
  protected ServiceRegistry getServiceRegistry() {
    return serviceRegistry;
  }

}
