#!/bin/sh -e
# Startup script for Red5

export RED5_HOME=/opt/matterhorn/red5

red5_start="$RED5_HOME/red5.sh"
red5_stop="$RED5_HOME/red5-shutdown.sh"

start() {
        echo -n "Starting Red5: "
        nohup ${red5_start} &
        echo "done."
}
stop() {
        echo -n "Shutting down Red5: "
        ${red5_stop}
        echo "done."
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 10
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
esac

exit 0


