list.name=ACL.DEFAULTS
# This list provider allows you to configure defaults for the Access Policy view
# in the event details, series details and access policy details.

# New access policy automatically have the read attribute set.
# Default: true
#read_enabled = true

# New access policy automatically have the write attribute set.
# Default: false
#write_enabled = false

# The read property of the displayed access policy cannot be changed
# Default: true
#read_readonly = true

# The write property of the displayed access policy cannot be changed
# Default: false
#write_readonly = false

# Default actions for every new role
# Default: No actions
#default_actions=annotate,annotate-admin

# ACL template that will automatically be applied to new events/series. This is useful if you would like a specific
# set of roles to always be applied to new events/series per default.
# The ACL templates are defined under /etc/acl.
# Set the file name as the value of the config key (without the file extension).
# Default: None
#default_template=private

# When switching to a new template, all roles that don't belong to the new template are removed
# To keep roles between template switches, specify role prefixes below
# Example: ROLE_AAI_USER_,ROLE_ADMIN
# Default: None
#keep_on_template_switch_role_prefixes=ROLE_USER_

# List of comma separated prefixes. If a role matches one of the given prefixes, it will not appear in the select
# role dropdowns. Can be useful if you have a category of roles that makes working with the access policy tab
# tedious, but that you need to keep around for other reasons.
# Default: No prefixes
#display_role_filter_blacklist_prefixes=ROLE_GROUP_
