version: '2'
services:
  elasticsearch:
    container_name: $COMPOSE_PROJECT_NAME-elasticsearch
    image: docker.io/library/elasticsearch:7.9.2
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
    environment:
      discovery.type: single-node
  activemq:
    container_name: $COMPOSE_PROJECT_NAME-activemq
    image: quay.io/lkiesow/activemq
    ports:
      - 127.0.0.1:61616:61616
    volumes:
      - ../activemq/activemq.xml:/activemq-opencast.tpl.xml:ro
  mariadb:
    container_name: $COMPOSE_PROJECT_NAME-mariadb
    image: docker.io/library/mariadb:10.5.9
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: opencast
      MYSQL_DATABASE: opencast
      MYSQL_USER: opencast
      MYSQL_PASSWORD: dbpassword
