<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>opencast-opensearch-impl</artifactId>
  <name>Opencast :: opensearch-impl</name>
  <packaging>bundle</packaging>
  <parent>
    <groupId>org.opencastproject</groupId>
    <artifactId>base</artifactId>
    <version>21-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <properties>
    <opencast.basedir>${project.basedir}/../..</opencast.basedir>
  </properties>
  <dependencies>
    <dependency>
      <groupId>org.opencastproject</groupId>
      <artifactId>opencast-opensearch-api</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.opencastproject</groupId>
      <artifactId>opencast-common</artifactId>
      <version>${project.version}</version>
    </dependency>
    <!-- osgi support -->
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>osgi.core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.service.component</artifactId>
    </dependency>
    <!-- opensearch -->
    <dependency>
      <groupId>org.opensearch.client</groupId>
      <artifactId>opensearch-rest-high-level-client</artifactId>
      <version>${opensearch.version}</version>
    </dependency>
    <dependency>
      <groupId>org.opensearch.client</groupId>
      <artifactId>opensearch-rest-client</artifactId>
      <version>${opensearch.version}</version>
    </dependency>
    <dependency>
      <groupId>org.opensearch</groupId>
      <artifactId>opensearch</artifactId>
      <version>${opensearch.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.opensearch</groupId>
      <artifactId>opensearch-core</artifactId>
      <version>${opensearch.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.opensearch</groupId>
      <artifactId>opensearch-x-content</artifactId>
      <version>${opensearch.version}</version>
    </dependency>
    <dependency>
      <groupId>org.opensearch</groupId>
      <artifactId>opensearch-common</artifactId>
      <version>${opensearch.version}</version>
    </dependency>
    <dependency>
      <groupId>org.opensearch.plugin</groupId>
      <artifactId>lang-mustache-client</artifactId>
      <version>${opensearch.version}</version>
    </dependency>
    <dependency>
      <groupId>org.opensearch.plugin</groupId>
      <artifactId>rank-eval-client</artifactId>
      <version>${opensearch.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents.client5</groupId>
      <artifactId>httpclient5</artifactId>
      <version>5.6.1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents.core5</groupId>
      <artifactId>httpcore5</artifactId>
      <version>5.4</version>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents.core5</groupId>
      <artifactId>httpcore5-h2</artifactId>
      <version>5.4</version>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents.core5</groupId>
      <artifactId>httpcore5-reactive</artifactId>
      <version>5.4</version>
    </dependency>
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-core</artifactId>
      <version>3.8.6</version>
    </dependency>
    <dependency>
      <groupId>org.apache.lucene</groupId>
      <artifactId>lucene-core</artifactId>
      <version>${lucene.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.lucene</groupId>
      <artifactId>lucene-join</artifactId>
      <version>${lucene.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.lucene</groupId>
      <artifactId>lucene-queryparser</artifactId>
      <version>${lucene.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.lucene</groupId>
      <artifactId>lucene-queries</artifactId>
      <version>${lucene.version}</version>
    </dependency>
    <dependency>
      <groupId>com.carrotsearch</groupId>
      <artifactId>hppc</artifactId>
      <version>0.8.1</version>
    </dependency>
    <dependency>
      <groupId>org.reactivestreams</groupId>
      <artifactId>reactive-streams</artifactId>
      <version>1.0.4</version>
    </dependency>
    <dependency>
      <groupId>org.snakeyaml</groupId>
      <artifactId>snakeyaml-engine</artifactId>
      <version>3.0.1</version>
    </dependency>
    <dependency>
      <groupId>tools.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>3.2.1</version>
    </dependency>
    <dependency>
      <groupId>tools.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>3.2.1</version>
    </dependency>
    <dependency>
      <groupId>tools.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-smile</artifactId>
      <version>3.2.1</version>
    </dependency>
    <dependency>
      <groupId>tools.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-yaml</artifactId>
      <version>3.2.1</version>
    </dependency>
    <dependency>
      <groupId>tools.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-cbor</artifactId>
      <version>3.2.1</version>
    </dependency>

    <!-- thirdparty -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
    </dependency>

    <!-- testing -->
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-reload4j</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <ignoredUnusedDeclaredDependencies>
            <ignoredUnusedDeclaredDependency>org.opensearch.plugin:lang-mustache-client</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>org.opensearch.plugin:rank-eval-client</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>org.opensearch:opensearch-common</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>org.reactivestreams:reactive-streams</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>org.snakeyaml:snakeyaml-engine</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>tools.jackson.core:jackson-core</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>tools.jackson.core:jackson-databind</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>tools.jackson.dataformat:jackson-dataformat-smile</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>tools.jackson.dataformat:jackson-dataformat-yaml</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>tools.jackson.dataformat:jackson-dataformat-cbor</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>org.apache.lucene:lucene-join</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>org.apache.lucene:lucene-queryparser</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>org.apache.lucene:lucene-queries</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>com.carrotsearch:hppc</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>org.slf4j:slf4j-reload4j</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>org.apache.httpcomponents.core5:httpcore5-h2</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>org.apache.httpcomponents.core5:httpcore5-reactive</ignoredUnusedDeclaredDependency>
            <ignoredUnusedDeclaredDependency>io.projectreactor:reactor-core</ignoredUnusedDeclaredDependency>
          </ignoredUnusedDeclaredDependencies>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.felix</groupId>
        <artifactId>maven-bundle-plugin</artifactId>
        <extensions>true</extensions>
        <configuration>
          <instructions>
            <Import-Package>
              !com.aayushatharva.brotli4j.*,
              !com.carrotsearch.randomizedtesting,
              !com.github.luben.zstd,
              !org.apache.commons.compress.compressors,
              !org.brotli.dec,
              !com.conversantmedia.util.*,
              !com.fasterxml.jackson.dataformat.smile,
              !com.fasterxml.jackson.dataformat.xml.*,
              !com.fasterxml.jackson.dataformat.yaml.*,
              !com.google.common.*,
              !com.google.protobuf.*,
              !com.jcraft.jzlib,
              !com.lmax.disruptor.*,
              !com.sun.jna.*,
              !com.sun.management*,
              !com.tdunning.*,
              !joptsimple.*,
              !org.HdrHistogram.*,
              !org.apache.kafka.clients.producer.*,
              !org.bouncycastle.crypto.*,
              !org.conscrypt,
              !org.newsclub.net.unix,
              !org.apache.logging.log4j.util.internal,
              !org.apache.logging.log4j.core*,
              !org.apache.lucene.*,
              !javax.activation.*,
              !javax.annotation,
              !javax.annotation.meta,
              !jdk.net,
              !jdk.incubator.vector,
              !java.lang.foreign,
              !java.nio.file.spi.*,
              !com.sun.nio.file,
              !org.opensearch.arrow.spi,
              !org.opensearch.cli.*,
              !org.opensearch.common.queue,
              !org.opensearch.geometry.*,
              !org.opensearch.javaagent.bootstrap,
              !org.opensearch.plugin.classloader,
              !org.opensearch.secure_sm.*,
              !org.opensearch.task.commons.*,
              !org.opensearch.telemetry.*,
              !org.jctools.queues.*,
              !org.jspecify.annotations,
              !org.locationtech.jts.geom.*,
              !org.locationtech.spatial4j.*,
              !org.roaringbitmap.*,
              !org.tartarus.*,
              !org.zeromq.*,
              !com.github.mustachejava.*,
              *
            </Import-Package>
            <Export-Package>
              org.apache.lucene.search,
              org.opencastproject.opensearch.impl;version=${project.version}
            </Export-Package>
            <Embed-Dependency>
              groupId=org.opensearch;scope=compile,
              groupId=org.opensearch.client;scope=compile,
              groupId=org.opensearch.plugin;scope=compile,
              groupId=org.apache.httpcomponents.client5;scope=compile,
              groupId=org.apache.httpcomponents.core5;scope=compile,
              groupId=tools.jackson.core;scope=compile,
              groupId=tools.jackson.dataformat;scope=compile,
              reactor-core,
              reactive-streams,
              snakeyaml-engine,
              hppc,
              lucene-core,
              lucene-join,
              lucene-queryparser,
              lucene-queries
            </Embed-Dependency>
            <_exportcontents>
              org.opensearch,
              org.opensearch.action,
              org.opensearch.action.admin.cluster.health,
              org.opensearch.action.admin.indices.delete,
              org.opensearch.action.bulk,
              org.opensearch.action.delete,
              org.opensearch.action.get,
              org.opensearch.action.index,
              org.opensearch.action.search,
              org.opensearch.action.support,
              org.opensearch.action.support.clustermanager,
              org.opensearch.action.update,
              org.opensearch.client,
              org.opensearch.client.indices,
              org.opensearch.cluster.health,
              org.opensearch.common.document,
              org.opensearch.common.time,
              org.opensearch.common.unit,
              org.opensearch.common.xcontent,
              org.opensearch.core.common.io.stream,
              org.opensearch.core.rest,
              org.opensearch.core.xcontent,
              org.opensearch.index.mapper,
              org.opensearch.index.query,
              org.opensearch.script,
              org.opensearch.search,
              org.opensearch.search.aggregations,
              org.opensearch.search.aggregations.bucket.terms,
              org.opensearch.search.builder,
              org.opensearch.search.sort,
            </_exportcontents>
          </instructions>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
