#!/usr/bin/env python3

import requests
import json

from jinja2 import Template


RELEASE_URL = 'https://api.github.com/repos/opencast/opencast/releases'
BRANCH_URL = 'https://api.github.com/repos/opencast/opencast/branches?per_page=100'

def get_release_branches(page):
    branches = requests.get(f"{BRANCH_URL}&page={page}", headers=headers).json()
    branch_names = map(lambda x: x['name'], branches)
    release_branches = filter(lambda x: x.startswith('r/') and x.endswith('.x') and not x.startswith('r/1.'),
                             branch_names)
    return len(branches), sorted(release_branches, reverse=True, key=lambda x: float(x.strip('r/.x')))


def main():
    releases = requests.get(RELEASE_URL, headers=headers).json()
    versions = map(lambda x: float(x['tag_name']), releases)
    stable = int(max(versions))
    stable_branch = f'r/{stable}.x'

    count = 100
    page = 1
    release_branches = []
    while count == 100:
        print(f"Getting page {page}")
        unfiltered_count, current_page = get_release_branches(page)
        count = unfiltered_count
        release_branches = release_branches + current_page
        print(f"Page is {current_page}")
        page += 1

    version_info = [{
        'name': 'develop',
        'branch': 'develop',
        'attribute': ''}]
    for branch in release_branches:
        name = branch.split('/')[-1]
        attribute = None
        if branch == stable_branch:
            attribute = 'stable'
        elif float(branch.strip('r/.x')) > stable:
            attribute = 'pre release'

        version_info.append({
            'name': name,
            'branch': branch,
            'attribute': attribute})

    with open('versions.js', 'w') as f:
        f.write('var versions = ' + json.dumps(version_info))

    with open('index.html.j2', 'r') as f:
        langing_page = Template(f.read())
    with open('index.html', 'w') as f:
        f.write(langing_page.render(version_info=version_info))

    with open('404.html.j2', 'r') as f:
        error_page = Template(f.read())
    with open('404.html', 'w') as f:
        f.write(error_page.render(stable_branch=stable_branch))


if __name__ == '__main__':
    main()
