# Dependabot Batcher v1.0.3

name: 'Dependabot Batcher for Paella 7'

# Controls when the workflow will run
on:
  pull_request:
    paths:
      - 'modules/engage-paella-player-7/**'
  push:
    paths:
      - 'modules/engage-paella-player-7/**'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-batcher-paella-7:
    name: 'Combine dependabot PRs'
    runs-on: ubuntu-latest
    steps:
  # Batches Dependabot PRs into one by merging them into a combined branch, then raising a new PR
      - name: 'Dependabot Batcher'
        uses: Legal-and-General/dependabot-batcher@v1.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} #required
          baseBranchName: 'r/13.x' #optional
          batchBranchName: 'paella7-batcher-updates'
          batchPullTitle: 'Batch Dependabot Updates for Paella 7'
