name: Maintenance » Ensure mvnw and not mvn

on:
  pull_request:
    paths:
      - '.github/**'
      - 'mvnw'
      - '.mvn/**'
  push:
    paths:
      - '.github/**'
      - 'mvnw'
      - '.mvn/**'

jobs:
  mvn-check:
    name: Ensure mvn isn't being used
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: check mvn isn't being used
        run: |
          if [ -n "$(grep -R 'mvn ' .github | grep -v 'name:')" ]; then
            exit 1
          fi
