name: Maintenance » Update Matrix Room Description

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*'

jobs:
  update-room-desc:
    name: Update Matrix Room
    runs-on: ubuntu-latest
    if: github.repository == 'opencast/opencast'
    steps:
      - name: update room description
        env:
          MATRIX_USER: ${{ secrets.MATRIX_BOT_USER }}
          MATRIX_TOKEN: ${{ secrets.MATRIX_BOT_TOKEN }}
          URL_TOPIC: 'https://matrix-client.matrix.org/_matrix/client/r0/rooms/!HBsLKoOIEEOkxAeQvC%3Amatrix.org/state/m.room.topic/'
        run: |
          TAGS="$(curl https://api.github.com/repos/opencast/opencast/tags | jq -r '.[].name')"
          MAJOR="$(echo "$TAGS" | sed 's/\..*$//' | sort --version-sort | tail -n1)"
          STABLE="$(echo "$TAGS" | sort --version-sort | tail -n1)"
          LEGACY="$(echo "$TAGS" | grep -v "^${MAJOR}" | sort --version-sort | tail -n1)"
          TOPIC='{"topic":"opencast.org\n–\nLatest releases: '"$STABLE, $LEGACY"'\n–\nJoin the technical meeting: Tuesday, 3:15 pm UTC at meet.opencast.video (p: welcome)"}'
          curl -s --fail -XPUT -H 'Content-Type: application/json' -d "${TOPIC}" "${URL_TOPIC}?access_token=${MATRIX_TOKEN}"
