name: Tests » LTI Tools

on:
  pull_request:
    paths:
      - .github/workflows/test-lti-tools.yml
      - modules/lti/**
  push:
    paths:
      - .github/workflows/test-lti-tools.yml
      - modules/lti/**

jobs:
  test-lti:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7

    - name: set up python
      uses: actions/setup-python@v6
      with:
        python-version: 3.13

    - name: install javascript dependencies
      working-directory: modules/lti/
      run: npm ci

    - name: type check
      working-directory: modules/lti/
      run: npx tsc --noEmit -p tsconfig.json

    - name: install selenium
      working-directory: modules/lti/
      run: pip install -r requirements.txt

    - name: running selenium tests
      working-directory: modules/lti/
      run: ./selenium-tests
