name: Tests » Documentation build

on:
  pull_request:
    paths:
      - '.github/workflows/test-documentation-build.yml'
      - 'docs/guides/**'
      - 'docs/checkstyle/check-docs.sh'
      - '**.md'
  push:
    paths:
      - '.github/workflows/test-documentation-build.yml'
      - 'docs/guides/**'
      - 'docs/checkstyle/check-docs.sh'
      - '**.md'
    branches-ignore:
      - 'opencast-auto-forward-merge/**' # Don't run on auto forward merges, as they should be triggered by workflow_call.
  workflow_call:
    inputs:
      ref:
        required: false
        type: string

jobs:

  # Check documentation with markdownlint and build it using mkdocs
  test-documentation:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{ inputs.ref || github.ref }}
        fetch-depth: 0
    - name: (DEBUG-INFO) Print checked-out HEAD commit (child workflow)
      if: github.event_name == 'workflow_call'
      run: |
        echo "CHILD_WORKFLOW_HEAD=$(git rev-parse HEAD)"
        echo "GITHUB_SHA=${{ github.sha }}"

    - name: set up python
      uses: actions/setup-python@v6
      with:
        python-version: 3.13

    - name: install mkdocs
      working-directory: docs/guides
      run: pip install -q -r requirements.txt

    - name: install javascript dependencies
      working-directory: docs/guides
      run: npm ci

    - name: check documentation
      run: ./docs/checkstyle/check-docs.sh
