name: Tests » Extra checkstyle checks

on:
  pull_request:
    paths:
      - '.github/workflows/test-configuration.yml'
      - 'etc/**'
      - 'docs/checkstyle/check-config.sh'
      - '**/pom.xml'
  push:
    paths:
      - '.github/workflows/test-configuration.yml'
      - 'etc/**'
      - 'docs/checkstyle/check-config.sh'
      - '**/pom.xml'

jobs:
  additional-checks:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: check configuration
      run: ./docs/checkstyle/check-config.sh
