name: Tests » Documentation build

on:
  pull_request:
    paths:
      - '.github/workflows/test-documentation-build.yml'
      - 'docs/guides/**'
      - 'docs/checkstyle/check-docs.sh'
      - '**.md'
  push:
    paths:
      - '.github/workflows/test-documentation-build.yml'
      - 'docs/guides/**'
      - 'docs/checkstyle/check-docs.sh'
      - '**.md'

jobs:

  # Check documentation with markdownlint and build it using mkdocs
  test-documentation:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v7

    - name: set up python
      uses: actions/setup-python@v7
      with:
        python-version: 3.13

    - name: install mkdocs
      working-directory: docs/guides
      run: pip install -q -r requirements.txt

    - name: install javascript dependencies
      working-directory: docs/guides
      run: npm ci

    - name: check documentation
      run: ./docs/checkstyle/check-docs.sh
