name: Tests » LTI Tools

on:
  pull_request:
    paths:
      - .github/workflows/test-lti-tools.yml
      - modules/lti/**
  push:
    paths:
      - .github/workflows/test-lti-tools.yml
      - modules/lti/**

jobs:
  test-lti:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7

    - name: install javascript dependencies
      working-directory: modules/lti/
      run: npm ci

    - name: install playwright browsers
      working-directory: modules/lti/
      run: npx playwright install --with-deps firefox

    - name: running playwright tests
      working-directory: modules/lti/
      run: npm run test:e2e
